version: "3.9"
services:
  trello:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trello-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
